portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
]

projects/urls.py
from django.urls import include, path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>', views.project_details, name='project_details'),
]

projects/models.py
from django.db import models
import datetime

from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_STANDARD

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField(default=datetime.date.today)
    last_updated = models.DateTimeField(auto_now=True)
    short_description = models.TextField(max_length=200)
    description = MarkdownField(rendered_field='text_rendered', validator=VALIDATOR_STANDARD)
    text_rendered = RenderedMarkdownField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from projects.models import Project
import pytz


# Create your views here.

def all_projects(request):
    # query te db to return all project objects
    projects = Project.objects.all()
    return render(request, 'projects/all_projects.html',
                    {'projects': projects})

def project_details(request, pk):
    projects = Project.objects.get(pk=pk)
    return render(request, 'projects/details.html',
    {'projects': projects})


# def all_projects(request):
#     user_timezone = request.GET.get('user_timezone', None)

#     if user_timezone is not None:
#         try:
#             user_tz = pytz.timezone(user_timezone)
#         except pytz.UnknownTimeZoneError:
#             user_tz = timezone.utc
#     else:
#         user_tz = timezone.utc

#     projects = Project.objects.all()

#     context = {
#         'projects': projects,
#         'user_timezone': user_tz,  # Pass the user's timezone to the template
#     }

#     return render(request, 'projects/all_projects.html', context)

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %} {% load static %} {% block content %}
<div class="container">
  <h1>Projects</h1>
  <div class="row">
    {% for project in projects %}
    <div class="col-md-4 mb-2">
      <div class="card">
        <img class="card-img-top custom-img" src="{% static project.image %}" />
        <div class="card-body custom-card-body">
          <div class="row">
            <h5 class="card-title col">{{ project.title }}</h5>
            <p class="col">Created: {{ project.date|date:"d.m.Y" }}</p>
          </div>
          <div class="row mb-2">
            <p class="card-text">{{ project.short_description | safe}}</p>
          </div>
          <div class="row">
            <div class="d-flex justify-content-center">
              <a href="{% url 'projects:project_details' project.pk %}" class="btn btn-primary stretched-link"> Read More </a>
            </div>
          </div>
        </div>
        <div class="card-footer text-center">
          <small class="text-muted"> Last updated: {{ project.last_updated|date:"H:i d.m.Y" }} </small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

projects/templates/projects/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>All projects</title>
    {% comment %} <script>
      document.addEventListener('DOMContentLoaded', function () {
        const url = new URL(window.location.href);
        const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;

        // Check if the user_timezone GET parameter is already set
        if (!url.searchParams.has('user_timezone')) {
          url.searchParams.set('user_timezone', timezone);
          window.location.href = url;
        }
      });
    </script> {% endcomment %}

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link href="{% static 'projects/styles/base.css' %}" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'projects:all_projects' %}"
          >Portfolio</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:all_projects' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:all_projects' %}">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
  </body>
</html>

projects/templates/projects/details.html
{% extends 'projects/base.html' %} {% load static %} {% block content %}
<h1>{{ projects.title }}</h1>
<div class="row">
  <div class="col-md-7 mb-2">
    <img src="{% static projects.image %}" alt="{{ "testimage"}}" width="100%" />
  </div>
  <div class="col-md-4">
    <h5 class=>About the project</h5>
    <p>{{ projects.short_description | safe}}</p>
    <h5>Built with:</h5>
    <p>{{ projects.technology }}</p>
  </div>
</div>
<div class="row">
  <h5>Detailed description</h5>
  <p>{{ projects.text_rendered | safe}}</p>
</div>

{% endblock %}